
/* =====================================================================================
   16. LEASES (IFRS 16) & BORROWINGS
   -------------------------------------------------------------------------------------
   Lessee leases (Johannesburg, Nairobi, London, Dubai offices, Harare cyber lab ...):
     at commencement  Dr Right-of-use asset / Cr Lease liability (PV of payments at the
                      incremental borrowing rate)
     every month      Dr Interest on lease liabilities (financing) / Cr Lease interest payable
                      Dr Lease interest payable + Lease liability / Cr Bank  (payment)
                      Dr Depreciation of ROU assets / Cr Accumulated depreciation - ROU
   Short-term (<= 12 months) and low-value leases use the IFRS 16.6 exemption (expensed).
   Lessor leases (tenants in Maxhub House) are operating leases -> rental income.
   ===================================================================================== */

CREATE TABLE leases (
    lease_id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    lease_number          VARCHAR(30)   NOT NULL UNIQUE,
    role                  VARCHAR(8)    NOT NULL DEFAULT 'lessee' CHECK (role IN ('lessee','lessor')),
    description           VARCHAR(200)  NOT NULL,
    asset_class           VARCHAR(20)   NOT NULL DEFAULT 'property' CHECK (asset_class IN ('property','vehicles','equipment','parking')),
    office_id             BIGINT        REFERENCES offices,
    property_id           BIGINT        REFERENCES properties,        -- lessor leases: which building
    vendor_id             BIGINT        REFERENCES vendors,           -- landlord (lessee leases)
    tenant_name           VARCHAR(150),                               -- lessor leases
    currency_code         CHAR(3)       NOT NULL REFERENCES currencies,
    commencement_date     DATE          NOT NULL,
    end_date              DATE          NOT NULL,
    term_months           SMALLINT      NOT NULL CHECK (term_months > 0),
    payment_amount        NUMERIC(16,2) NOT NULL CHECK (payment_amount >= 0),  -- per period, lease currency
    payment_frequency     VARCHAR(10)   NOT NULL DEFAULT 'monthly' CHECK (payment_frequency IN ('monthly','quarterly','annual')),
    payment_timing        VARCHAR(8)    NOT NULL DEFAULT 'advance' CHECK (payment_timing IN ('advance','arrears')),
    annual_escalation_pct NUMERIC(5,2)  NOT NULL DEFAULT 0,
    discount_rate_pct     NUMERIC(6,3)  NOT NULL DEFAULT 0,          -- incremental borrowing rate (annual)
    initial_direct_costs  NUMERIC(16,2) NOT NULL DEFAULT 0,
    lease_incentives      NUMERIC(16,2) NOT NULL DEFAULT 0,
    deposit_paid          NUMERIC(16,2) NOT NULL DEFAULT 0,
    extension_option      TEXT,                                       -- "reasonably certain" assessment note
    exemption             VARCHAR(12)   CHECK (exemption IN ('short_term','low_value')),  -- IFRS 16.5-8
    rou_account_code      VARCHAR(20)   NOT NULL DEFAULT '1600',
    rou_acc_dep_account_code VARCHAR(20) NOT NULL DEFAULT '1601',
    initial_liability     NUMERIC(18,2),                              -- lease currency
    initial_rou_asset     NUMERIC(18,2),                              -- USD (non-monetary, historical rate)
    commencement_fx_rate  NUMERIC(18,8) NOT NULL DEFAULT 1,           -- lease currency -> USD
    liability_usd_balance NUMERIC(18,2) NOT NULL DEFAULT 0,           -- maintained by posting routines
    last_fx_rate          NUMERIC(18,8),
    status                VARCHAR(12)   NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','terminated','expired')),
    recognised_journal_id BIGINT        REFERENCES journal_entries,
    notes                 TEXT,
    CHECK (end_date > commencement_date)
);

-- Amortisation schedule (lease currency). Generated by fn_generate_lease_schedule().
CREATE TABLE lease_schedule (
    lease_id          BIGINT        NOT NULL REFERENCES leases ON DELETE CASCADE,
    period_no         SMALLINT      NOT NULL,
    period_date       DATE          NOT NULL,          -- first day of the month
    opening_liability NUMERIC(18,2) NOT NULL,
    payment           NUMERIC(18,2) NOT NULL,
    interest          NUMERIC(18,2) NOT NULL,
    principal         NUMERIC(18,2) NOT NULL,
    closing_liability NUMERIC(18,2) NOT NULL,
    rou_depreciation  NUMERIC(18,2) NOT NULL,          -- USD
    is_posted         BOOLEAN       NOT NULL DEFAULT FALSE,
    journal_entry_id  BIGINT        REFERENCES journal_entries,
    PRIMARY KEY (lease_id, period_no)
);

CREATE TABLE borrowings (
    loan_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    loan_number      VARCHAR(30)   NOT NULL UNIQUE,
    lender           VARCHAR(150)  NOT NULL,
    purpose          VARCHAR(200),
    currency_code    CHAR(3)       NOT NULL DEFAULT 'USD' REFERENCES currencies,
    principal        NUMERIC(18,2) NOT NULL CHECK (principal > 0),
    interest_rate_pct NUMERIC(6,3) NOT NULL,
    drawdown_date    DATE          NOT NULL,
    term_months      SMALLINT      NOT NULL,
    monthly_instalment NUMERIC(16,2),                  -- level instalment (annuity)
    security         VARCHAR(200),                     -- e.g. mortgage bond over Maxhub House
    bank_account_id  BIGINT        REFERENCES bank_accounts,
    status           VARCHAR(10)   NOT NULL DEFAULT 'active' CHECK (status IN ('active','repaid','default'))
);

CREATE TABLE loan_schedule (
    loan_id          BIGINT        NOT NULL REFERENCES borrowings ON DELETE CASCADE,
    period_no        SMALLINT      NOT NULL,
    due_date         DATE          NOT NULL,
    opening_balance  NUMERIC(18,2) NOT NULL,
    instalment       NUMERIC(18,2) NOT NULL,
    interest         NUMERIC(18,2) NOT NULL,
    principal        NUMERIC(18,2) NOT NULL,
    closing_balance  NUMERIC(18,2) NOT NULL,
    is_posted        BOOLEAN       NOT NULL DEFAULT FALSE,
    journal_entry_id BIGINT        REFERENCES journal_entries,
    PRIMARY KEY (loan_id, period_no)
);
