[theme]
primaryColor = "#0E2C52"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FA"
textColor = "#14213D"
font = "sans serif"

[server]
headless = false
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
